spring:
  application:
    name: profile-service
  neo4j:
    uri: ${DB_URL:bolt://localhost:7687}
    authentication:
      username: ${DB_USERNAME:neo4j}
      password: ${DB_PASSWORD:12345678}

server:
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: /profile
